#!/usr/bin/env bash
#
# Step 2: Deploy the ARM template for VNet Flow Logs Forwarder.
#
# This creates all the pipeline infrastructure:
#   - Event Hub Namespace + Hub + Consumer Group
#   - Event Grid System Topic + Subscription (BlobCreated -> Event Hub)
#   - Cursor Storage Account + Table
#   - Function App Storage Account
#   - App Service Plan (Dynamic or Premium)
#   - Function App (shell only — code deployed in Step 3)
#
# Prerequisites:
#   - Step 1 has been run (resource group + storage account exist with flow logs)
#   - NR_LICENSE_KEY is exported in the current shell
#
# Usage:
#   export NR_LICENSE_KEY="your-key-here"
#   export SUFFIX="abc123"     # Must match Step 1
#   ./step2-deploy-arm-template.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=config.env
source "$SCRIPT_DIR/config.env"

ARM_TEMPLATE="$REPO_ROOT/armTemplates/azuredeploy-vnetflowlogsforwarder.json"

: "${NR_LICENSE_KEY:?ERROR: Set NR_LICENSE_KEY in your shell before running this script}"

echo "=============================================="
echo " Step 2: Deploy ARM Template"
echo "=============================================="
echo "  Resource Group : $RG"
echo "  Location       : $LOC"
echo "  Template       : $ARM_TEMPLATE"
echo "  NR Endpoint    : $NR_ENDPOINT"
echo "  Storage (src)  : $STORAGE"
echo "  Suffix         : $SUFFIX"
echo "=============================================="
echo

# -----------------------------------------------------------------------------
# Pre-flight checks
# -----------------------------------------------------------------------------
preflight() {
  if ! az account show >/dev/null 2>&1; then
    echo "Not logged into Azure CLI. Initiating login..."
    az login
  fi

  if ! az group show -n "$RG" >/dev/null 2>&1; then
    echo "ERROR: Resource group $RG not found. Run step1-enable-vnet-flowlogs.sh first." >&2
    exit 1
  fi

  if ! az storage account show -n "$STORAGE" -g "$RG" >/dev/null 2>&1; then
    echo "ERROR: Storage account $STORAGE not found. Run step1-enable-vnet-flowlogs.sh first." >&2
    exit 1
  fi

  if [[ ! -f "$ARM_TEMPLATE" ]]; then
    echo "ERROR: ARM template not found at: $ARM_TEMPLATE" >&2
    exit 1
  fi

  echo "  ✓ Pre-flight checks passed."
  echo
}

# -----------------------------------------------------------------------------
# Deploy ARM template
# -----------------------------------------------------------------------------
deploy_arm_template() {
  echo "Deploying ARM template (this may take 3-5 minutes)..."
  echo

  local deployment_name="vnetflow-deploy-$(date +%Y%m%d%H%M%S)"

  az deployment group create \
    --name "$deployment_name" \
    --resource-group "$RG" \
    --template-file "$ARM_TEMPLATE" \
    --parameters \
      newRelicLicenseKey="$NR_LICENSE_KEY" \
      sourceStorageAccountName="$STORAGE" \
      newRelicEndpoint="$NR_ENDPOINT" \
      deployFunctionApp=false \
    --output none

  echo "  ✓ ARM template deployed successfully."
  echo
}

# -----------------------------------------------------------------------------
# Capture outputs
# -----------------------------------------------------------------------------
capture_outputs() {
  echo "Deployment outputs:"
  local outputs
  outputs=$(az deployment group show \
    --resource-group "$RG" \
    --name "$(az deployment group list -g "$RG" --query '[0].name' -o tsv)" \
    --query properties.outputs -o json 2>/dev/null || echo "{}")

  FUNC_APP_NAME=$(echo "$outputs" | grep -o '"functionAppName"[^}]*"value":"[^"]*"' | grep -o '"value":"[^"]*"' | cut -d'"' -f4 || echo "")
  SOURCE_STORAGE=$(echo "$outputs" | grep -o '"sourceStorageAccountName"[^}]*"value":"[^"]*"' | grep -o '"value":"[^"]*"' | cut -d'"' -f4 || echo "")
  EH_NAMESPACE=$(echo "$outputs" | grep -o '"eventHubNamespace"[^}]*"value":"[^"]*"' | grep -o '"value":"[^"]*"' | cut -d'"' -f4 || echo "")
  EH_NAME_OUT=$(echo "$outputs" | grep -o '"eventHubName"[^}]*"value":"[^"]*"' | grep -o '"value":"[^"]*"' | cut -d'"' -f4 || echo "")
  CURSOR_STORAGE=$(echo "$outputs" | grep -o '"cursorStorageAccountName"[^}]*"value":"[^"]*"' | grep -o '"value":"[^"]*"' | cut -d'"' -f4 || echo "")

  echo "  Function App       : ${FUNC_APP_NAME:-<not found>}"
  echo "  Source Storage     : ${SOURCE_STORAGE:-<not found>}"
  echo "  Event Hub NS       : ${EH_NAMESPACE:-<not found>}"
  echo "  Event Hub          : ${EH_NAME_OUT:-<not found>}"
  echo "  Cursor Storage     : ${CURSOR_STORAGE:-<not found>}"

  # Save outputs to a file for Step 3
  cat > "$SCRIPT_DIR/.arm-outputs.env" <<EOF
# Auto-generated by step2-deploy-arm-template.sh — used by step3
FUNC_APP_NAME="${FUNC_APP_NAME}"
SOURCE_STORAGE="${SOURCE_STORAGE}"
EH_NAMESPACE="${EH_NAMESPACE}"
EH_NAME_OUT="${EH_NAME_OUT}"
CURSOR_STORAGE="${CURSOR_STORAGE}"
EOF
  echo
  echo "  Outputs saved to: scripts/.arm-outputs.env"
}

# -----------------------------------------------------------------------------
# Verify deployment
# -----------------------------------------------------------------------------
verify() {
  echo
  echo "--- Resources created ---"
  az resource list -g "$RG" -o table
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
main() {
  preflight
  deploy_arm_template
  capture_outputs
  verify
  echo
  echo "=============================================="
  echo " Step 2 COMPLETE"
  echo "=============================================="
  echo
  echo "The ARM template created:"
  echo "  - Event Hub Namespace + Hub + Consumer Group"
  echo "  - Event Grid Topic + Subscription (BlobCreated -> Event Hub)"
  echo "  - Cursor Storage Account + Table"
  echo "  - Function App (empty — code not deployed yet)"
  echo
  echo "Next: Run step3-deploy-function-and-test.sh to deploy the function code"
  echo "      and verify logs arrive in New Relic."
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
